name = "mission-control-hq"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
ENVIRONMENT = "development"
REGION_ID = "us-east-1"
DEPLOYMENT_ID = "dev-local"
CANARY_PERCENT = "0"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "RATE_LIMITS_DEV"
preview_id = "RATE_LIMITS_PREVIEW"

[[kv_namespaces]]
binding = "AUDIT_LOG"
id = "AUDIT_LOG_DEV"
preview_id = "AUDIT_LOG_PREVIEW"

[[kv_namespaces]]
binding = "DEAD_MAN_FUSE"
id = "DEAD_MAN_FUSE_DEV"
preview_id = "DEAD_MAN_FUSE_PREVIEW"

[env.staging]
name = "mission-control-hq-staging"

[env.staging.vars]
ENVIRONMENT = "staging"
REGION_ID = "us-west-2"
DEPLOYMENT_ID = "staging-v1"
CANARY_PERCENT = "10"

[[env.staging.kv_namespaces]]
binding = "RATE_LIMITS"
id = "818488f4ab134ff4b5c8abfc1b0014b4"

[[env.staging.kv_namespaces]]
binding = "AUDIT_LOG"
id = "51fe5bc11953476982404ad01edc7e30"

[[env.staging.kv_namespaces]]
binding = "DEAD_MAN_FUSE"
id = "94a9fa3289434dbda96b02acf86b8bea"

[env.production]
name = "mission-control-hq-production"

[env.production.vars]
ENVIRONMENT = "production"
REGION_ID = "us-east-1"
DEPLOYMENT_ID = "prod-v1"
CANARY_PERCENT = "0"

[[env.production.kv_namespaces]]
binding = "RATE_LIMITS"
id = "4baff5e9e15140a781b6440d6d797694"

[[env.production.kv_namespaces]]
binding = "AUDIT_LOG"
id = "a615dbc35dee45808d3971ebf17adb19"

[[env.production.kv_namespaces]]
binding = "DEAD_MAN_FUSE"
id = "bd868c4bc23c45fe97a661b2d39159da"

[observability]
enabled = true