name = "mission-control-hq"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
ENVIRONMENT = "development"

[env.staging]
name = "mission-control-hq-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "mission-control-hq-production"
vars = { ENVIRONMENT = "production" }

[observability]
enabled = true